import streamlit as st
from PIL import Image

# --- Configurazione pagina ---
st.set_page_config(
    page_title="Statistical App",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        "About": "Created by Mathsly Research"
    }
)

# --- Mostra logo in sidebar ---
with st.sidebar:
    logo_path = "Logo.jpg"  # assicurati che il file sia nella stessa directory oppure specifica il path corretto
    try:
        st.image(logo_path, width=300)
    except:
        st.warning("⚠️ Logo not found. Please upload 'logo.jpeg'")

    st.markdown("""
    ---
    ## Legal Protection
    © 2025 Maria Luisa Garo. All rights reserved.  
    This software, including its code, texts, interface structure, and conceptual design,  
    is protected by copyright laws and international treaties.  
    Any copying, even partial, reproduction, modification, distribution, or unauthorized use is strictly prohibited.  
    Violations will be prosecuted to the fullest extent of the law.

    ---
    ## Protezione Legale
    © 2025 Maria Luisa Garo. Tutti i diritti riservati.  
    Questo software, compresi il codice, i testi, la struttura dell’interfaccia e l’idea progettuale,  
    è protetto dalle leggi sul diritto d'autore e da trattati internazionali.  
    È vietata qualsiasi copia, anche parziale, riproduzione, modifica, distribuzione o utilizzo non autorizzato.  
    Ogni violazione sarà perseguita legalmente.
    """)

# --- Titolo principale ---
st.title("📊 Statistical Analysis App")

# --- Indice operativo ---
st.markdown("""
### 🚀 How to use this App:
1. **Upload your dataset**  
2. **Explore variable distributions**  
3. **Run statistical tests**  
4. **View results summary**

---
""")

# --- Sezione Privacy & Disclaimer con accettazione ---
with st.expander("💡 Privacy & Disclaimer (Click to Read)", expanded=True):
    st.markdown("""
    ### Privacy
    - I dati caricati dagli utenti (dataset) e le elaborazioni effettuate tramite questa applicazione **non vengono salvati né visualizzati** da noi in alcun modo.
    - Tutto il processo avviene **localmente** sul server che esegue l'applicazione.

    ### Responsabilità
    - L'analisi prodotta è generata automaticamente da un sistema algoritmico e **non costituisce una consulenza professionale**.
    - Non ci assumiamo alcuna responsabilità per eventuali errori, interpretazioni errate o decisioni prese sulla base dei risultati forniti.
    - **Si raccomanda di verificare autonomamente i risultati** prima di un loro utilizzo ufficiale o decisionale.

    ---
    ### Privacy & Disclaimer (English Version)
    - Uploaded datasets and all analyses performed through this application are **neither saved nor viewed** by us in any way.
    - All processing takes place **locally** on the server running the application.

    - The analysis is automatically generated by an algorithmic system and **does not constitute professional advice**.
    - We accept **no responsibility** for any errors, misinterpretations, or decisions made based on the results provided.
    - **Users are strongly encouraged to independently verify** all results before using them in any official or decision-making context.
    """)

accepted = st.checkbox("I have read and understood the Privacy & Disclaimer.", value=False)

if not accepted:
    st.warning("⚠️ Please acknowledge the Privacy & Disclaimer before proceeding.")
    st.stop()
else:
    st.success("📅 Thank you for accepting the Privacy & Disclaimer. You can proceed!")
    
